# Generated by Django 3.2.12 on 2022-06-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('chinese_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='中文名')),
                (
                    'system_role',
                    models.CharField(
                        choices=[('admin', 'Admin'), ('user', 'User')],
                        default='user',
                        max_length=32,
                        verbose_name='系统角色',
                    ),
                ),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='首次登录时间')),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='组 ID')),
                ('name', models.CharField(max_length=128, verbose_name='组名称')),
                ('bindings', models.JSONField(default=list, verbose_name='绑定人员')),
                (
                    'type',
                    models.CharField(
                        choices=[('system', '系统分组'), ('fixed', '固定分组'), ('dynamic', '动态分组'), ('specific', '指定分组')],
                        default='dynamic',
                        max_length=32,
                        verbose_name='组类型',
                    ),
                ),
            ],
            options={
                'db_table': 'account_user_group',
            },
        ),
    ]
